namespace RicKit.Tools.Localization
{
    // 可以修改成自己用的语言枚举
    public enum LanguageEnum
    {
        Unset = -1,
        English,
        French,
        German,
        Portuguese,
        Spanish,
        Italian,
        Hungarian,
        Dutch,
        Polish,
        Czech,
        Swedish,
        Romanian,
        Danish,
        Finnish,
        Indonesian,
        Norwegian,
        Bulgarian,
        Croatian,
        Estonian,
        Greek,
        Icelandic,
        Latvian,
        Lithuanian,
        Luxembourgish,
        Russian,
        SerboCroatian,
        Slovak,
        Slovenian,
        Turkish,
        Ukrainian,
        Arabic,
        ChineseSimplified,
        ChineseTW,
        Hindi,
        Japanese,
        Korean,
        Malay,
        Thai,
        Vietnamese,
    }
}
